### ISSUE TITLE
Why the .jpg file?

### ISSUE THREAD

**Issue by crowne** [rdash/rdash-angular#101]
Hi thanks for this template, I find it to be an excellent tool for learning and I like the tech-stack that has been chosen.
Sorry for raising this as an issue, but I would like to understand the thought process behind the design.

Why did you choose to use avatar.jpg for the user icon in the top right corner, instead of using font-awesome which is already bundled and used elsewhere?

**Comment by Ehesp** [comment]
Just for looks really since it's more interesting than an icon. You can use icons as normal if you want though.
