### ISSUE TITLE
Login Template

### ISSUE THREAD

**Issue by dBer** [rdash/rdash-angular#134]
I'm trying to do a login view, but I see the same structure that in the rest of the web, I can see the menu and the navbar.

Can you help me with this? How can I remove these parts in the login view?

Thanks!

**Comment by dBer** [comment]
Solved with 2 differents views, one with base and other with menu.

**Comment by abhitechgithub** [comment]
But I couldn't solve that, I am trying to use state.current.name to identify state on index.html to have two different view but state.currentname does nothing
